### ISSUE TITLE
Get the build/target actually working

### ISSUE THREAD

**Issue by amoeba** [amoeba/metacat-index-poller#1]
I wanna get this working:

1. Clone
2. `mvn package`
3. `java -cp target/metacat-index-poller-1.0-SNAPSHOT.jar edu.ucsb.nceas.Main`

But when I get to step 3 currently, I get:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/hazelcast/client/ClientConfig
	at edu.ucsb.nceas.Main.main(Main.java:40)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.client.ClientConfig
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 1 more
```

**Comment by amoeba** [comment]
Fixed! Turns out you have to do some pom magic.

```xml
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>edu.ucsb.nceas.MetacatIndexPoller</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```
